name: CI

on:
  push:
    branches:
      - main
      - qa

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: qa
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
